theme: jekyll-theme-primer
title: Motivation
description: Predicting crime in US Metropolitan Statistical Areas
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
